name: Deploy to reg.ru
# Рабочий deploy с созданием контейнера ubuntu:13.04
# ubuntu:13.04 нужна для использования GLIBC 2.17 в сборке api_app 

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Клонирует репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2

      # Устанавливает Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Создание Docker образа
      - name: Build Docker image
        run: |
          echo "FROM ubuntu:13.04

          RUN sed -i 's|http://archive.ubuntu.com/ubuntu|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list
          RUN apt-get update && apt-get install -y wget tar ca-certificates

          RUN wget -q --no-check-certificate https://go.dev/dl/go1.22.4.linux-amd64.tar.gz
          RUN tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz
          ENV PATH=/usr/local/go/bin:$PATH
          RUN go version
          RUN ldd --version

          COPY . /app
          WORKDIR /app
          RUN go mod download
          RUN GOOS=linux GOARCH=amd64 go build -o api_app .

          " > Dockerfile

          docker build -t my-app-image .

      # Создание контейнера и копирование скомпилированного файла
      - name: Create Docker container and copy binary
        run: |
          docker create --name my-app-container my-app-image true
          docker cp my-app-container:/app/api_app ./api_app
          docker rm my-app-container

      # Настраивает SSH для подключения к серверу
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # сканирует SSH ключи сервера и добавляет их в файл known_hosts, чтобы избежать ошибки проверки подлинности хоста
      - name: Add server to known_hosts
        run: |
          ssh-keyscan website-reg.ru >> ~/.ssh/known_hosts

      # создает директорию /app на вашем сервере, если она не существует
      - name: Create directory on server
        run: |
          ssh user@website-reg.ru 'mkdir -p ~/app'
          ssh user@website-reg.ru 'mkdir -p ~/app/db'

      # Передает приложение и миграционные файлы на сервер, останавливает старую версию приложения, 
      # устанавливает MySQL клиент, выполняет миграции и запускает новую версию приложения.
      - name: Deploy to server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DB_DRIVER: mysql
          DB_SOURCE_TESTSQLC: root:secret@tcp(localhost:3306)/main_db?parseTime=true
          DB_SOURCE: ${{ secrets.DB_SOURCE }}
          SERVER_ADDRESS: 0.0.0.0:8080
          TOKEN_SYMMETRIC_KEY: ${{ secrets.TOKEN_SYMMETRIC_KEY }}
          ACCESS_TOKEN_DURATION: 15m
          REFRESH_TOKEN_DURATION: 24h
        run: |
          echo "Copying files to server..."
          scp -r ./api_app user@website-reg.ru:~/app
          scp -r ./db/migration user@website-reg.ru:~/app/db

          echo "Copying environment variables to server..."
          ssh user@website-reg.ru << 'EOF'
            echo "DB_DRIVER=mysql" > ~/app/app.env
            echo "DB_SOURCE_TESTSQLC=\"root:secret@tcp(localhost:3306)/main_db?parseTime=true\"" >> ~/app/app.env
            echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" >> ~/app/app.env
            echo "DB_SOURCE=\"${{ secrets.DB_SOURCE }}\"" >> ~/app/app.env
            echo "SERVER_ADDRESS=0.0.0.0:8080" >> ~/app/app.env
            echo "TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY }}" >> ~/app/app.env
            echo "ACCESS_TOKEN_DURATION=15m" >> ~/app/app.env
            echo "REFRESH_TOKEN_DURATION=24h" >> ~/app/app.env
          EOF

          echo "Checking contents of ~/app on server..."
          ssh user@website-reg.ru 'ls -la ~/app'

          echo "Running deployment commands on server..."
          ssh user@website-reg.ru << 'EOF'
            set -e
            echo "Stopping existing application..."
            pkill api_app || true

            if ! command -v mysql &> /dev/null
            then
              echo "MySQL client could not be found"
              exit 1
            fi

            echo "Applying database migrations..."
            set -o allexport; source ~/app/app.env; set +o allexport
            ~/migrate -path ~/app/db/migration -database $DATABASE_URL -verbose up

            echo "Deploying new version..."
            cd ~/app
            ./api_app &
            
            echo "Deployment completed!"
          EOF



